---
title: "Gulf of Maine Monitoring and Basin Oyster Restoration Site Leaflet Maps"
output: 
  html_document:
    toc: TRUE
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r packages, echo=FALSE}

# install packages

## install.packages("tidyverse")
## install.packages("leaflet")

library(tidyverse) ## For plotting and data wrangling.
library(leaflet) ## For leaflet interactive maps

# library(sf) ## For spatial data
# library(RColorBrewer) ## For colour palettes
# library(htmltools) ## For html
# library(leafsync) ## For placing plots side by side
# library(kableExtra) ## Table output
```

```{r}

# read maine_buoys csv

maine_buoys <- read_csv("data/maine_buoy.csv")

```

# Gulf of Maine Buoy Data

```{r leaflet-gulf-of-maine}

# create marker labels for gulf of maine leaflet

labels <- sprintf(
  "<strong>%s</strong><br/><strong>location:</strong> %s<br/><strong>Type:</strong> %s<br/><strong>Link:</strong> %s",
    maine_buoys$name, 
    maine_buoys$location, 
    maine_buoys$category,
    maine_buoys$link) %>% 
      lapply(htmltools::HTML) 


# Generate gulf of maine leaflet
## OpenStreetMap chosen because of extensive labeling (helpful when exploring a mapping tool)

leaflet(maine_buoys) %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.OceanBasemap) %>%
  addMarkers(~lon, ~lat, popup = ~labels) %>%
    setView(lng = -69, lat = 43.7, zoom = 7.5)  

  
```

# Phippsburg Basin Project Site

```{r leaflet-phippsburg-basin}

# Generate basin leaflet
## Esri.WorldImagery chosen to help better visualize the natural environment around the basin

basin <- data.frame(
  name = "The Basin",
  location = "Phippsburg, Maine",
  category = "Ocean",
  link = NA,
  notes = "Oyster restoration site", 
  lon = -69.852308,
  lat = 43.805930
)

leaflet(basin) %>%
  addTiles() %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addProviderTiles(providers$CartoDB.VoyagerOnlyLabels) %>%
  addMarkers(~lon, ~lat) %>%
  setView(lng = -69.855, lat = 43.805, zoom = 14) 
```